select * from products;
select * from product_price_audit;
select * from deletion_log;
update products set price = price * .7 where product_id in (5, 10);
update products set price = price * .9;
update products set name = 'Organic Chemistry' where product_id = 2;
insert into products values (13, 5, 'Easy Listening', 'Kenny G Classics', 19.99);
insert into products values (14, 5, 'Phantom of the Opera', null, null);
delete from products where product_id = 12;
delete from products where product_id = 2;
delete from products where product_type_id = 3;
delete from products where price < 15;
delete from products where product_id = 5;
insert into products values (15, 6, 'Comedy', null, 12.99);
delete from products where product_id = 6;
update products set price = price - .05;
select * from products;
select * from product_price_audit;
select * from deletion_log;